# Generated by Django 4.2 on 2023-05-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('linenos', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'snippet',
                'ordering': ['created'],
            },
        ),
    ]
