# Generated by Django 4.2 on 2023-05-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ME', 'Mechanical'), ('CE', 'Civil'), ('EE', 'Electrical'), ('EC', 'Electronics')], max_length=50)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.student')),
            ],
        ),
    ]
