# Generated by Django 4.2 on 2023-05-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Student',
        ),
    ]
