# Generated by Django 4.2 on 2023-05-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_remove_department_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
