# Generated by Django 4.2 on 2023-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
